#!/usr/bin/env python3
from pathlib import Path
import json,re,html
R=Path(__file__).resolve().parents[1]
plan=json.loads((R/'data/complete_plan.json').read_text())
items=json.loads((R/'data/runtime_items.json').read_text())['items']
lua=int(re.search(r'LUA_FIXTURE_CHECKS=(\d+)',(R/'release-tests/lua-v03.log').read_text()).group(1))
cs=(R/'release-tests/csharp-v033.log').read_text();core=int(re.search(r'CORE_FIXTURE_CHECKS=(\d+)',cs).group(1));native=int(re.search(r'NATIVE_FIXTURE_CHECKS=(\d+)',cs).group(1));image=int(re.search(r'IMAGE_SCAN_FIXTURE_CHECKS=(\d+)',cs).group(1));capture=int(re.search(r'CAPTURE_FIXTURE_CHECKS=(\d+)',cs).group(1))
project={'name':'WD1 Chinese In-Game Toolkit','version':'0.3.3-alpha','as_of':'2026-09-14','is_finished_trainer':False,'scope':'game-internal progression, resources, minigames, inventory; no platform-achievement module','steam_appid_for_game_identity_only':243470,'observed_build':'11241563','observed_profile':'profiles/steam-11241563-observed.json','supported_game_fingerprints':[],'runtime_game_tests_completed':False,'platform_achievement_module':{'included':False,'source_and_binaries_removed':True},'user_plan':'plan/用户确认的完整计划.md','structured_plan':'data/complete_plan.json','original_gameplay_acceptance_retained':'plan/original_gameplay_requirements.json','infinite_and_add_are_independent':True,'native_candidate_controls':sum(x['backend']=='NATIVE_CANDIDATE' for x in plan['items']),'curated_item_keys':len(items),'complete_plan_entries':len(plan['items']),'unbound_entries':sum(x['backend']=='UNBOUND' for x in plan['items']),'candidate_warning':'Candidate implementation is not game verification or guaranteed complete semantic coverage.','runtime_dependencies':{'desktop':'.NET Framework 4.8 family / Windows x64','native_panel':'none beyond Windows/.NET; no CE needed','lua_plugin':'NexusTools >=1.1.12, separately installed, unverified on user build'},'safety':{'no_auto_enable':True,'native_scan_readonly':True,'native_capture_modifies_code':True,'native_and_persistent_lua_require_backup':True,'activity_detection':'manual scope, not automatic identification','native_object_capture':'stable fresh pointer only; semantic ownership not certified','unknown_binary_rejected':True},'test_counts':{'lua_fixture_assertions':lua,'core_file_checks':core,'native_fake_process_checks':native,'image_scan_checks':image,'capture_checks':capture,'live_game_or_windows_testing':False},'user_confirmed_context':{'os':'Windows 11 Pro 24H2 26100 x64','edition':'Steam Complete Edition','bad_blood_starts':True,'initial_mods':'none','dlc':['dlc_exclusive','dlc_pill_people','dlc_seasonpass','dlc_solo','ulc_pack'],'online_game_progress':'all unfinished, user statement','diagnostic_save_candidates':0},'remaining_input':'Optional read-only WD1-Native-Probe.json and verbal results; no screenshots, credentials or memory dumps requested.'}
(R/'project.json').write_text(json.dumps(project,ensure_ascii=False,indent=2)+'\n')
(R/'release-tests/results.json').write_text(json.dumps({'version':'0.3.3-alpha','date':'2026-09-14','compiler':'Mono mcs C# 7.2 + Microsoft .NET Framework 4.8 reference assemblies (explicit, no default stdlib)' ,'environment':'Linux + Mono + Lua 5.1 + Xvfb','lua_checks':lua,'core_checks':core,'native_checks':native,'image_scan_checks':image,'capture_checks':capture,'ui_smoke_windows':2,'real_game_test':False,'windows_runtime_test':False,'platform_account_connection':False},indent=2)+'\n')
# This release contains only current docs. Historical sources remain in the previously delivered v0.2 ZIP.
for name in ['技术路线与资料.md','Steam成就49项.md','接口证据-v0.2.md']:(R/'docs'/name).unlink(missing_ok=True)
(R/'docs/功能范围与验收.md').write_text('# 当前功能范围与验收入口\n\n以 `plan/用户确认的完整计划.md` / `data/complete_plan.json` 为唯一完整计划。无限与增加分别保留；全武器/全衣服/全物品是独立操作。\n\n169 个控件/需求记录中有未绑定项，不是 169 项可用作弊功能。原逐项游戏验收保留在 `plan/original_gameplay_requirements.json`。所有候选均未真实游戏验证。\n')
# Replace stale preparation metadata catalogs with current scope; original gameplay snapshot remains separate.
(R/'data/feature_requirements.json').unlink(missing_ok=True);(R/'data/feature_requirements.csv').unlink(missing_ok=True)
(R/'THIRD-PARTY-NOTICES.md').write_text('''# 依赖与来源声明 · v0.3

原创 C#、Lua、控制器、界面、安全流程与测试采用 MIT。没有 Ubisoft、Valve、NexusTools 或公开表作者背书。

## 独立宿主
NexusTools / Troplo 只作为 Lua 插件宿主，用户自行安装；本包不捆绑 ASI、代理 DLL、安装器或完整自带 Trainer。Lua 函数/数据参考公开 Trainer 提交 a20b61be0e2e00258ccb10ccfeb1be78c9b60450：https://github.com/Troplo/NexusTools.Trainer 。原始事实键保持来源，本项目未换皮上游 Trainer。

## 原生候选证据
公开 WD-Trainer v1.0 / Vortex Prime（2026，https://fearlessrevolution.com/viewtopic.php?t=30038 ）提供 v1.06.329 候选的指令和字段事实。
Daijobu 汇总表及 gir489 / NanoByte / redleouf / HiSaZuL（https://fearlessrevolution.com/viewtopic.php?t=2310 ）提供旧版饮酒/库存等事实。未运行或捆绑 CT，不重打包商业工具，只引用有限互操作事实；控制/捕获/生成/检查代码原创。

旧版平台成就模块及第三方桥接源码/二进制已从新版本移除。不包含该模块的依赖，也不触碰平台账号状态。Steam仅用于本游戏安装定位、版本身份和用户主动启动。

没有游戏 EXE/引擎、原生客户端 DLL、存档、账号文件或内存转储。构建工具 Mono/Python/Lua/Xvfb 不打包。Windows运行依赖 .NET Framework 4.8 系列。所有自编译二进制未签名。
''')
# Compact network-independent guide; links are document navigation, not program launch simulations.
summary='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WD1 v0.3.3</title><style>body{background:#0d1625;color:#e8f2ff;font:16px/1.8 system-ui,"Microsoft YaHei UI";margin:0}main{max-width:1000px;margin:auto;padding:40px 28px}h1{font-size:42px;color:#50d5b4;line-height:1.3}.card{background:#18263d;padding:25px;border:1px solid #354b64;border-radius:12px;margin:20px 0}h2{margin-top:0}code{color:#a5f2d7}b.warn{color:#f2ca82}li{margin:8px 0}a{color:#50d5b4}.small{font-size:13px;color:#b3c5dc}</style><main><p>WD1 中文游戏内工具箱 · v0.3.3 Alpha · 目标 build 11241563</p><h1>无限与增加，都保留。<br>游戏进度，不是平台成就。</h1><div class="card"><b class="warn">这是实际编译的更新测试版，不是全功能完成版。</b><p>原生候选控件 24 个、白名单奖励键 218 个；完整计划 169 条持续保留。候选/清单/开关不等于游戏验证。尚未接通的功能没有被删除，也不会假亮起。</p><p>全武器、全衣服、全物品三个独立批次已接入当前模式白名单。无限库存资源与增加资源分别控制；公共库存保护包含备弹，不假装成每一种材料的独立地址。</p></div><div class="card"><h2>01 / 先只读扫描，最快判断可适配项</h2><ol><li>整个包独立解压，不要覆盖旧目录。打开 <code>WD1-Toolkit.exe</code>。</li><li>选择真实游戏根目录，正常进入单机游戏。</li><li>游戏内参数 → 打开独立参数控制面板 → <b>只读连接 / 扫描</b>。</li><li>点击“导出诊断（失败也可）”保存 <code>WD1-Native-Probe.json</code>。连接失败也能导出；这一阶段不改代码/数值，无需 CE 或宿主。</li></ol></div><div class="card"><h2>02 / 使用原生独立开关</h2><ol><li>先保存、退出游戏，在管理工具手选真实存档并校验备份。之前报告没有找到存档，不代表备份完成。</li><li>重新进游戏，打开参数面板，确认单机与实际活动。</li><li>数值项先“捕获所选对象”，回游戏触发菜单/活动，查看执行次数/状态并核对原始值；暂停后的缓存只供查看，不用抢2秒。</li><li>无限/冻结勾选对应行；增加/减少选中行填数值，按“排队一次增减”，等待同一对象的新心跳；30秒无刷新自动取消。增加不会开启无限。</li><li>切换活动前停止全部；退出面板前恢复代码并断开。</li></ol><b class="warn">捕获会安装临时跳转，不再是纯只读扫描。手选模式不是自动识别；对象稳定也不证明属于玩家。首轮一项一项验证。</b></div><div class="card"><h2>03 / 游戏内 Lua 菜单</h2><p>独立安装作者 NexusTools ≥1.1.12，关闭游戏后用管理工具安装本项目插件；本体 / Bad Blood 完全退出后切换。按 Insert / Pause / Ctrl+\\ → WD1 KIT → ARM。</p><p>无敌、持续弹药/专注、单次弹药、单项材料增加、全武器/全衣服/全物品批次分别控制。批次先“准备”，再 CONFIRM；STOP不回收已写入的奖励。</p><p>给予物品不等于永久拥有、叫车可用或游戏内任务完成；需正常存档后重启核验。</p></div><div class="card"><h2>完整计划持续跟进</h2><p><a href="完整计划.html">查看可搜索完整计划</a>，或打开 <code>plan/用户确认的完整计划.md</code>。Spider/Madness/Alone独立成长、饮酒光标、Cash Run/NVZN/车辆/赛车计时、玩家1–4、全部游戏进度与其他原需求都还在。</p><p><b class="warn">尚未绑定的项目不能改游戏。</b> 不用普通技能点/同一钱包/全局暂停，冒充所有小游戏和四个玩家。</p></div><div class="card"><h2>安全与反馈</h2><p>备份常见位置是 Ubisoft Connect 安装目录 <code>savegames\\账号\\541</code>；手选实际 .save/.save.*/.sav 文件夹，别选 GamerProfile.xml。备份保存在本机工具数据目录，不自动上传。</p><p>工具异常退出、无法恢复代码时，完全退出游戏再重启。没有代码签名，不要求关闭安全软件、UAC或防火墙。恢复文件成功不证明游戏可读档。</p><p>无需截图、密码、完整存档或内存转储；使用脱敏候选报告和口述数字前后反馈。</p></div><p class="small">实际测试：Lua '''+str(lua)+''' 个断言（包含逐物品检查），文件核心 '''+str(core)+''' 项，原生模拟进程 '''+str(native)+''' 项；两窗口 Linux Mono/Xvfb 冒烟。真实游戏与 Windows 原生 ABI 尚未测试。详细说明 README.zh-CN.md / docs；源码、许可与 SHA256SUMS.txt 随包。</p></main></html>'''
(R/'开始使用.html').write_text(summary)
print('metadata updated',project['native_candidate_controls'],len(items),lua,core,native)
